// Generated by CoffeeScript 1.10.0
(function() {
  var assert, builder, guts, should;

  should = require('should');

  assert = require('assert');

  builder = require('botbuilder');

  guts = require('../guts');

  describe('Echo Bot', function() {
    return it('should talk smack', function(done) {
      var reply;
      reply = guts.process('hello');
      assert(reply === 'You said: hello');
      return done();
    });
  });

}).call(this);

//# sourceMappingURL=echo_test.js.map
