// Generated by CoffeeScript 1.10.0
(function() {
  var Guts;

  Guts = (function() {
    function Guts() {}

    Guts.prototype.process = function(message) {
      return "You said: " + message;
    };

    return Guts;

  })();

  module.exports = new Guts();

}).call(this);

//# sourceMappingURL=guts.js.map
